runtime: java17
env: standard

instance_class: F2

handlers:
  - url: /.*
    script: auto

logging:
  level:
    org.apache.coyote.http11: INFO
    org.apache.tomcat.util.net: INFO
    org.apache.catalina: INFO
