spring.application.name=Chat




spring.datasource.url=jdbc:h2:mem:tg_bot;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml


spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

logging.level.org.apache.coyote.http11=DEBUG
logging.level.org.apache.coyote.http11.Http11Processor=TRACE

server.tomcat.connection-timeout=10s
logging.level.org.apache.coyote=ERROR

server.port=${PORT:8080}
server.ssl.enabled=false
